//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Mvc5Application1.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Message {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Mvc5Application1.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Please select).
        /// </summary>
        internal static string Dropdownlist_Select {
            get {
                return ResourceManager.GetString("Dropdownlist_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Header row name, please use the valid template file.
        /// </summary>
        internal static string IMPORT_Common_Invalid_Header_Row_Name {
            get {
                return ResourceManager.GetString("IMPORT_Common_Invalid_Header_Row_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download template error.
        /// </summary>
        internal static string IMPORT_DRAWING_DownloadError {
            get {
                return ResourceManager.GetString("IMPORT_DRAWING_DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred reading the file, please select a valid Excel file and try again.
        /// </summary>
        internal static string IMPORT_DRAWING_File_Corrupt {
            get {
                return ResourceManager.GetString("IMPORT_DRAWING_File_Corrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data validation failed, please see the highlighted cells in the file for detail.
        /// </summary>
        internal static string IMPORT_DRAWING_Import_Failed {
            get {
                return ResourceManager.GetString("IMPORT_DRAWING_Import_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data importing completed, please see the results in the file for detail.
        /// </summary>
        internal static string IMPORT_DRAWING_Import_Successfully {
            get {
                return ResourceManager.GetString("IMPORT_DRAWING_Import_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Header row name, please use the valid template file.
        /// </summary>
        internal static string IMPORT_DRAWING_Invalid_Header_Row_Name {
            get {
                return ResourceManager.GetString("IMPORT_DRAWING_Invalid_Header_Row_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated Payroll Numbers, please keep 1 line only.
        /// </summary>
        internal static string IMPORT_Employee_Duplicate_PayrollNumber {
            get {
                return ResourceManager.GetString("IMPORT_Employee_Duplicate_PayrollNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Payroll Number can contains only alphanumeric and “.”, “-” characters, please correct and try again.
        /// </summary>
        internal static string Import_Employee_InvalidPayrollNumberFormat {
            get {
                return ResourceManager.GetString("Import_Employee_InvalidPayrollNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value, please correct and try again.
        /// </summary>
        internal static string IMPORT_Employee_InvalidValue {
            get {
                return ResourceManager.GetString("IMPORT_Employee_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length for {0} is 50 characters, please correct and try again.
        /// </summary>
        internal static string IMPORT_Employee_Max_Length {
            get {
                return ResourceManager.GetString("IMPORT_Employee_Max_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Employee is imported.
        /// </summary>
        internal static string IMPORT_Employee_NoEmployee_Imported {
            get {
                return ResourceManager.GetString("IMPORT_Employee_NoEmployee_Imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred reading the file, please select a valid Excel file and try again.
        /// </summary>
        internal static string IMPORT_Excel_File_Corrupt {
            get {
                return ResourceManager.GetString("IMPORT_Excel_File_Corrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum file size is 10MB. Please try again..
        /// </summary>
        internal static string IMPORT_FileSizeLimit {
            get {
                return ResourceManager.GetString("IMPORT_FileSizeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill-in all the required cells.
        /// </summary>
        internal static string IMPORT_Required_Cell {
            get {
                return ResourceManager.GetString("IMPORT_Required_Cell", resourceCulture);
            }
        }
    }
}
